### ISSUE TITLE
Monitor network requests in real time

### ISSUE THREAD

**Issue by deutranium** [jackbisceglia/MLH-Ethical-Data#3]
Allow the users to monitor the incoming and outgoing data from the system through requests by showing them the following:

- The referrer domain: Which website/IP made the request
- The location to view the data
- Type of request
- Incoming/outgoing

Try to find the python packages which can be used for the same and figure out an implementation as a part of a CLI

**Comment by jackbisceglia** [comment]
After some research, it seems like this is possible but I'm not quite sure what our approach would be. 

One idea I had was perhaps we could pivot this into data monitoring for a web server. Maybe we could monitor traffic in and out of a web server and log it to a file, and perhaps analyze it?

**Comment by deutranium** [comment]
I was thinking something like the following:

1. The user types the app name and goes into a CLI
2. The user can type the commands to use a particular feature. For example:
    - `monitor -url google.com` will list the current requests incoming/outgoing from any google.com domain
    - `monitor` will list all the requests incoming/outgoing from any domain
    - `monitor -out` will monitor outgoing requests
    - `monitor -in` will monitor incoming requests
    - `monitor <arguments here> -log <file path> can log the output to a file

**Comment by jackbisceglia** [comment]
I was looking into this, and it seems like it's essentially just packet sniffing, which doesn't seem like a very Python-dependent thing. I'll do some more research later on and let you know and in the meantime perhaps you could give it a quick look
